NAME: 'EMA Crossover'
MODULE: 'ema_crossover'
CLASS: 'EMAcrossOver'
INTERVAL: '1d'
PERIOD: 30
RISK_PC: 2
SIZING: 'risk'
PARAMETERS:
  slow_ema: 50
  fast_ema: 21
  RR: 1.0

# Define pairs to monitor
WATCHLIST: ['^NSEI']