NAME: 'MACD Trend Strategy'
MODULE: 'macd'
CLASS: 'SimpleMACD'
INTERVAL: '1w'
PERIOD: 30
RISK_PC: 1
SIZING: 'risk'
PARAMETERS:
  ema_period: 200
  MACD_fast: 12
  MACD_slow: 26
  MACD_smoothing: 9
  
  # Exit level parameters
  RR: 1.5

WATCHLIST: ['^NSEBANK']
            # 'EURJPY=X',
            # 'EURAUD=X',
            # 'AUDJPY=X']
            